eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.52:8011/eureka/,http://10.0.0.46:8012/eureka,http://10.0.0.64:8013/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
